// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	file_application "go-back-comp/internal/files/application"
	file_infrastructure "go-back-comp/internal/files/infrastructure"
)

// Injectors from wire.go:

func InitializeFileHandler() *file_infrastructure.FileHandler {
	fileRepository := file_infrastructure.NewFileRepository()
	fileService := file_application.NewFileService(fileRepository)
	fileHandler := file_infrastructure.NewFileHandler(fileService)
	return fileHandler
}
